# Generated by Django 4.2.4 on 2024-09-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0003_dcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessOwner',
            fields=[
                ('po_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
