# Generated by Django 4.2.4 on 2024-09-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0004_processowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProcedure',
            fields=[
                ('policy_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('process_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.processowner')),
            ],
        ),
    ]
