# Generated by Django 4.2.4 on 2024-09-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0005_policyprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.policyprocedure')),
            ],
        ),
    ]
