# Generated by Django 4.2.4 on 2024-09-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0008_hcbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCReport',
            fields=[
                ('nc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_incident', models.DateField()),
                ('project_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('scenario_details', models.TextField()),
                ('justification', models.TextField()),
                ('potential_fi', models.CharField(max_length=100)),
                ('non_fi', models.CharField(max_length=100)),
                ('level_impact', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('nc_rating', models.CharField(max_length=100)),
                ('remarks_bgcm', models.TextField()),
                ('remarks_hcbd', models.TextField()),
                ('clarification_date', models.DateField(blank=True, null=True)),
                ('nc_decision', models.CharField(max_length=100)),
                ('remarks_po', models.TextField()),
                ('action', models.TextField()),
                ('acknowledgment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_completed', 'Not Completed'), ('completed', 'Completed'), ('closed', 'Closed')], default='not_completed', max_length=20)),
                ('bgcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.bgcm')),
                ('dcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.dcc')),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.doer')),
                ('hcbd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.hcbd')),
                ('process_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.processowner')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.scenario')),
            ],
        ),
    ]
