# Generated by Django 4.2.4 on 2024-09-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0017_ncreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NCReport',
        ),
    ]
