# Generated by Django 4.2.4 on 2024-09-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0018_delete_ncreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(default='Policy', max_length=255)),
                ('process_owner', models.CharField(default='Process Owner', max_length=255)),
                ('dateIncident', models.DateField()),
                ('typeRef', models.TextField()),
                ('refNo', models.TextField()),
                ('conProjectName', models.TextField()),
                ('accName', models.TextField()),
                ('poDivision', models.TextField()),
                ('scenarioDetails', models.TextField()),
                ('catJus', models.TextField()),
                ('poFI', models.TextField()),
                ('nonFI', models.TextField()),
                ('levelImpact', models.TextField()),
                ('frequency', models.TextField()),
                ('ncRating', models.TextField()),
                ('doerJustification', models.TextField()),
                ('remarksBGCM', models.TextField()),
                ('remarksHCBD', models.TextField()),
                ('clarificationDate', models.TextField()),
                ('ncDecision', models.TextField()),
                ('remarksPO', models.TextField()),
                ('action', models.TextField()),
                ('acknowledgment', models.BooleanField(default=False)),
                ('doerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.doer')),
                ('scenarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.scenario')),
            ],
        ),
    ]
