# Generated by Django 4.2.4 on 2024-09-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0035_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rate',
        ),
    ]
