# Generated by Django 4.2.4 on 2024-10-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0042_ncreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NCReport',
        ),
    ]
