# Generated by Django 4.2.4 on 2024-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0046_ncreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('admin_email', models.TextField()),
            ],
        ),
    ]
