# Generated by Django 4.2.4 on 2024-10-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0051_delete_hcbd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BGCM',
        ),
    ]
