# Generated by Django 4.2.4 on 2024-10-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0057_ncreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
