# Generated by Django 4.2.4 on 2024-10-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0059_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BGCM',
        ),
    ]
