# Generated by Django 4.2.4 on 2024-10-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0060_delete_bgcm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGCM',
            fields=[
                ('bgcm_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('bgcm_email', models.EmailField(max_length=254)),
                ('bgcm_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_compliance_automation_process.division')),
            ],
        ),
    ]
