# Generated by Django 4.2.4 on 2024-10-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_compliance_automation_process', '0063_hcbd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NCReport',
        ),
    ]
